env:
  NAME: ulid
name: Release
on:
  push:
    tags: [v*]
  pull_request:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  build-linux-gnu:
    name: Build & Release for linux
    needs:
      - create-release
    strategy:
      fail-fast: false
      matrix:
        postgres: [14, 15]
        box:
          - runner: ubuntu-20.04
            arch: amd64
          - runner: buildjet-2vcpu-ubuntu-2204-arm
            arch: arm64
    runs-on: ${{ matrix.box.runner }}
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          # Add postgres package repo
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null

          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git build-essential libpq-dev curl libreadline6-dev zlib1g-dev pkg-config cmake
          sudo apt-get install -y --no-install-recommends libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache
          sudo apt-get install -y --no-install-recommends clang libclang-dev llvm-dev gcc tree

          # Install requested postgres version
          sudo apt-get install -y postgresql-${{ matrix.postgres }} postgresql-server-dev-${{ matrix.postgres }} -y

          # Ensure installed pg_config is first on path
          export PATH=$PATH:/usr/lib/postgresql/${{ matrix.postgres }}/bin

          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile minimal --default-toolchain 1.68.0 && \
            rustup --version && \
            rustc --version && \
            cargo --version

          # Ensure cargo/rust on path
          source "$HOME/.cargo/env"

          cargo install cargo-pgx --version 0.7.3 --locked
          cargo pgx init --pg${{ matrix.postgres }}=/usr/lib/postgresql/${{ matrix.postgres }}/bin/pg_config

          # selects the pgVer from pg_config on path
          # https://github.com/tcdi/pgx/issues/288
          cargo pgx package --no-default-features --features pg${{ matrix.postgres }}
      - name: Set variables
        id: vars
        env:
          PKG_DIR: ${{ env.NAME }}-v0.1.0-pg${{ matrix.postgres }}-${{ matrix.box.arch }}-linux-gnu
        shell: bash
        run: echo "PKG_DIR=$PKG_DIR" >> $GITHUB_OUTPUT
      - name: Build artifacts
        run: |
          # Create installable package
          mkdir archive
          cp `find target/release -type f -name "${{ env.NAME }}*"` archive

          # Copy files into directory structure
          mkdir -p ${{ env.PKG_DIR }}/usr/lib/postgresql/lib
          mkdir -p ${{ env.PKG_DIR }}/var/lib/postgresql/extension
          cp archive/*.so ${{ env.PKG_DIR }}/usr/lib/postgresql/lib
          cp archive/*.control ${{ env.PKG_DIR }}/var/lib/postgresql/extension
          cp archive/*.sql ${{ env.PKG_DIR }}/var/lib/postgresql/extension

          # symlinks to Copy files into directory structure
          mkdir -p ${{ env.PKG_DIR }}/usr/lib/postgresql/${{ matrix.postgres }}/lib
          cd ${{ env.PKG_DIR }}/usr/lib/postgresql/${{ matrix.postgres }}/lib
          cp -s ../../lib/*.so .
          cd ../../../../../..

          mkdir -p ${{ env.PKG_DIR }}/usr/share/postgresql/${{ matrix.postgres }}/extension
          cd ${{ env.PKG_DIR }}/usr/share/postgresql/${{ matrix.postgres }}/extension

          cp -s ../../../../../var/lib/postgresql/extension/${{ env.NAME }}.control .
          cp -s ../../../../../var/lib/postgresql/extension/${{ env.NAME }}*.sql .
          cd ../../../../../..

          # Create install control file
          extension_version=v0.1.0
          # strip the leading v
          deb_version=${extension_version:1}

          mkdir -p ${{ env.PKG_DIR }}/DEBIAN
          touch ${{ env.PKG_DIR }}/DEBIAN/control
          echo 'Package: ${{ env.NAME }}' >> ${{ env.PKG_DIR }}/DEBIAN/control
          echo 'Version:' ${deb_version} >> ${{ env.PKG_DIR }}/DEBIAN/control
          echo 'Architecture: ${{ matrix.box.arch }}' >> ${{ env.PKG_DIR }}/DEBIAN/control
          echo 'Maintainer: Pavan Sunkara' >> ${{ env.PKG_DIR }}/DEBIAN/control
          echo 'Description: A PostgreSQL extension for ULID' >> ${{ env.PKG_DIR }}/DEBIAN/control

          # Create deb package
          sudo chown -R root:root ${{ env.PKG_DIR }}
          sudo chmod -R 00755 ${{ env.PKG_DIR }}
          sudo dpkg-deb --build --root-owner-group ${{ env.PKG_DIR }}
      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ env.PKG_DIR }}.deb
          asset_name: ${{ env.PKG_DIR }}.deb
          asset_content_type: application/vnd.debian.binary-package
